server.port: 18200

logging:
  level.org.cdteam.employee: DEBUG
swagger.enable: true
mybatis-plus:
  mapper-locations: mybatis/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
cdteam.web:
  base-packages: org.cdteam.employee  #  验证码
  verification-code:
    #  验证码类型配置 查看 VerificationCodeEnum 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    heigth: 36
    # 内容长度
    length: 2
  security:
    ignore-urls: /swagger-resources/configuration/ui,/swagger-resources,/v2/api-docs,/swagger-ui/,/actuator/health,/druid/**
    # 账号单用户 登录
    single-login: false
    header: Authorization
    token-key: 'USOP-APP-AUTH:OAUTH-TOKEN:'
    # 必须使用最少88位的Base64对该令牌进行编码
    base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
    # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
    token-validity-in-seconds: 14400000
    # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
    detect: 1800000
    # 续期时间范围，默认1小时，单位毫秒
    renew: 3600000
---
# 开发环境配置
spring:
  profiles: remote
  datasource:
    url: jdbc:mysql://47.106.129.111:3306/employees?useOldAliasMetadataBehavior=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: ue88824568==321
    driver-class-name: com.mysql.jdbc.Driver

---
# 本地运行环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employees?useOldAliasMetadataBehavior=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

