export default {
    GET_USER_INFO: 'GET_USER_INFO',
    INIT_PERMISSION: 'INIT_PERMISSION',
    LOGIN: 'LOGIN',
    EXIT: 'EXIT',
    SYSTEM_TOKEN_KEY: 'SYSTEM_TOKEN_KEY_V2',
    LOAD_ALL_PRODUCT: 'LOAD_ALL_PRODUCT',
    // LOAD_ALL_CHANNEL: 'LOAD_ALL_CHANNEL',
    LOAD_ALL_ORG: 'LOAD_ALL_ORG',
    SYSTEM_INIT: 'SYSTEM_INIT',
    CHANGE_CURRENT_ORG: 'CHANGE_CURRENT_ORG',
    LOAD_UNREAD_MESSAGE: 'LOAD_UNREAD_MESSAGE',
    LOAD_ALL_DETAILS: 'LOAD_ALL_DETAILS',
    CHANGE_MENU: 'CHANGE_MENU',
    // LOAD_VISIT_COUNT: 'LOAD_VISIT_COUNT',
    LOAD_USER_TODO_NUMBER: 'LOAD_USER_TODO_NUMBER',
    LOAD_ALL_PERMISSION: 'LOAD_ALL_PERMISSION',
    INIT_WEB_SOCKET: 'INIT_WEB_SOCKET'
}
