export default {
    SUPPLIER_ATTACHMENT_TYPE: 'SUPPLIER_ATTACHMENT_TYPE',
    TOKEN_KEY: 'TOKEN_KEY',
    SYS_CODE_SETTLEMENT_SCOPE: 'SETTLEMENT_SCOPE',
    SYS_CODE_PAY_CONFIG: 'PAY_CONFIG',
    SYS_CODE_SPECIAL_PRODUCT_CODE: 'SPECIAL_PRODUCT_CODE',
    SYS_CODE_BROKEN_ORDER_STATUS: 'BROKEN_ORDER_STATUS',
    SYS_CODE_BROKEN_ORDER_TYPE: 'BROKEN_ORDER_TYPE',
    SYS_CODE_SEVIECE_URL: 'SEVIECE_URL',
    SYS_CODE_RISK_BROKEN_SCREEN_C: 'RISK_BROKEN_SCREEN_C',
    SYS_CODE_RISK_TYPE: 'RISK_TYPE',
    SYS_CODE_RISK_ORDER_TYPE: 'RISK_ORDER_TYPE',
    SYS_CODE_EXPRESS_COMPANY: 'EXPRESS_COMPANY',
    SYS_CODE_HIGH_END_PRDID: 'HIGH_END_PRDID',
    SYS_CODE_TICKET_TO_TYPE: 'TICKET_TO_TYPE',
    SYS_CODE_TICKET_TYPE: 'TICKET_TYPE',
    SYS_CODE_LEND_TYPE: 'LEND_TYPE',
    SYS_CODE_BOSSVERIFYSTATUS: 'BOSSVERIFYSTATUS',
    SYS_CODE_SHOPBOSSVERIFYSTATUS: 'SHOPBOSSVERIFYSTATUS',
    SYS_CODE_CLOSE_TYPE: 'CLOSE_TYPE',
    SYS_CODE_MALLORDERTYPE: 'MALLORDERTYPE',
    SYS_CODE_PRD_DISTYPE: 'PRD_DISTYPE',
    SYS_CODE_SALESMANSTATUS: 'SALESMANSTATUS',
    SYS_CODE_ISCHENGJIAO: 'ISCHENGJIAO',
    SYS_CODE_REJECT_USERNAME: 'REJECT_USERNAME',
    SYS_CODE_REJECT_LOG: 'REJECT_LOG',
    SYS_CODE_NOW_EXAM_CONFIG: 'NOW_EXAM_CONFIG',
    SYS_CODE_CLOSE_STATUS: 'CLOSE_STATUS',
    SYS_CODE_BUSINESS_TYPE: 'BUSINESS_TYPE',
    SYS_CODE_PAYFAILINFO: 'PAYFAILINFO',
    SYS_CODE_EX_PROCE_TYPE: 'EX_PROCE_TYPE',
    SYS_CODE_POST_REC_TIME: 'POST_REC_TIME',
    SYS_CODE_REFUNDSTATUS: 'REFUNDSTATUS',
    SYS_CODE_SHS_COMMON: 'SHS_COMMON',
    SYS_CODE_SHS_OFFLINE: 'SHS_OFFLINE',
    SYS_CODE_SHS_ONLINE: 'SHS_ONLINE',
    SYS_CODE_SHS: 'SHS',
    SYS_CODE_PRDRETURNTYPE: 'PRDRETURNTYPE',
    SYS_CODE_REJECT_REASON: 'REJECT_REASON',
    SYS_CODE_PAYSTATUS: 'PAYSTATUS',
    SYS_CODE_ORDERPAYTYPE: 'ORDERPAYTYPE',
    SYS_CODE_SELCHECKTYPE: 'SELCHECKTYPE',
    SYS_CODE_CHANNEL_CONFIG: 'CHANNEL_CONFIG',
    SYS_CODE_CHECKTYPE_M: 'CHECKTYPE_M',
    SYS_CODE_SNPAYSTATUS: 'SNPAYSTATUS',
    SYS_CODE_SNORDERSTATUS: 'SNORDERSTATUS',
    SYS_CODE_SNACCOUNTTYPE: 'SNACCOUNTTYPE',
    SYS_CODE_SNBANK: 'SNBANK',
    SYS_CODE_ISSHOWSELL: 'ISSHOWSELL',
    SYS_CODE_ISPAYUPLOAD: 'ISPAYUPLOAD',
    SYS_CODE_MALLINVSTATUS: 'MALLINVSTATUS',
    SYS_CODE_SYSMODEL: 'SYSMODEL',
    SYS_CODE_CLERRORLEVEL: 'CLERRORLEVEL',
    SYS_CODE_CHANNELLEVEL: 'CHANNELLEVEL',
    SYS_CODE_SALETYPE: 'SALETYPE',
    SYS_CODE_CHANNELLOGOTYPE: 'CHANNELLOGOTYPE',
    SYS_CODE_MALLORDERSTATUS: 'MALLORDERSTATUS',
    SYS_CODE_TARGETTYPE: 'TARGETTYPE',
    SYS_CODE_PRDSALETYPE: 'PRDSALETYPE',
    SYS_CODE_MALLINVTYPE: 'MALLINVTYPE',
    SYS_CODE_OFFORDERSTATUS: 'OFFORDERSTATUS',
    SYS_CODE_ORDERSTATUS: 'ORDERSTATUS',
    SYS_CODE_PRDORDERSTATUS2: 'PRDORDERSTATUS2',
    SYS_CODE_OUTPOSTCOMP: 'OUTPOSTCOMP',
    SYS_CODE_PAYFROMTYPE: 'PAYFROMTYPE',
    SYS_CODE_PAYTOTYPE: 'PAYTOTYPE',
    SYS_CODE_CHECKTYPE: 'CHECKTYPE',
    SYS_CODE_CHANNELBRAND: 'CHANNELBRAND',
    SYS_CODE_PRDPROPER: 'PRDPROPER',
    SYS_CODE_USERTYPE: 'USERTYPE',
    SYS_CODE_CHECKLEVEL: 'CHECKLEVEL',
    SYS_CODE_BANKTYPE: 'BANKTYPE',
    SYS_CODE_FINANCEACCOUNTYYPE: 'FINANCEACCOUNTYYPE',
    SYS_CODE_ORDERTYPE: 'ORDERTYPE',
    SYS_CODE_COMACCOUNT: 'COMACCOUNT',
    SYS_CODE_POSTCOMP: 'POSTCOMP',
    SYS_CODE_USERTHEMES: 'USERTHEMES',
    SYS_CODE_AREATYPE: 'AREATYPE',
    SYS_CODE_DEPTTYPE: 'DEPTTYPE',
    SYS_CODE_ORGTYPE: 'ORGTYPE',
    SYS_CODE_STATUSLIST: 'STATUSLIST',
    SYS_CODE_PRDFINSTATUS: 'PRDFINSTATUS',
    SYS_CODE_CHANNELTYPE: 'CHANNELTYPE',
    SYS_CODE_SYSPARAM: 'SYSPARAM',
    SYS_CODE_PRDORDERSTATUS: 'PRDORDERSTATUS',
    SYS_CODE_PRICETMPTYPE: 'PRICETMPTYPE',
    SYS_CODE_PRDINVSTATUS: 'PRDINVSTATUS',
    SYS_CODE_PRDCHECKSTATUS: 'PRDCHECKSTATUS',
    SYS_CODE_INVORDERTYPE: 'INVORDERTYPE',
    SYS_CODE_PRDEXPROCSTATUS: 'PRDEXPROCSTATUS',
    SYS_CODE_AGENT_DETAIL_TYPE: 'AGENT_DETAIL_TYPE',
    SYS_CODE_AGENT_DETAIL_FROM: 'AGENT_DETAIL_FROM',
    SYS_CODE_AGENT_DETAIL_STATUS: 'AGENT_DETAIL_STATUS',
    SYS_CODE_REPORT_DATA_TYPE: 'REPORT_DATA_TYPE',
    SYS_CODE_REPORT_EQUAL_TYPE: 'REPORT_EQUAL_TYPE',
    SYS_CODE_REPORT_DEFVAL_TYPE: 'REPORT_DEFVAL_TYPE',
    SYS_CODE_REPORT_REF_TYPE: 'REPORT_REF_TYPE',
    SYS_CODE_REPORT_SHOW_TYPE: 'REPORT_SHOW_TYPE',
    SYS_CODE_RISK_STATUS: 'RISK_STATUS',
    SYS_CODE_SETTLEMENT_TYPE: 'SETTLEMENT_TYPE',
    SYS_CODE_SETTLEMENT_STATUS: 'SETTLEMENT_STATUS',
    SYS_CODE_SUPPLIER_TYPE: 'SUPPLIER_TYPE',
    SYS_CODE_REWARD_POLICY_TYPE: 'REWARD_POLICY_TYPE',
    SYS_CODE_RENTAL_ORDER_STATUS: 'RENTAL_ORDER_STATUS',
    SYS_CODE_RENTAL_ORDER_TYPE: 'RENTAL_ORDER_TYPE',
    SYS_CODE_CHANNEL_TOP_LEVEL: 'CHANNEL_TOP_LEVEL',
    SYS_CODE_SETTLEMENT_RULE_TYPE: 'SETTLEMENT_RULE_TYPE',
    SYS_CODE_BOX_STATUS: 'BOX_STATUS',
    SYS_CODE_PERMISSION_TYPE: 'PERMISSION_TYPE',
    CLIENT_TYPE_RISK_BROKEN_SUPPLIER: 1,
    CLIENT_CODE_ZHONGAN: 'ZHONGAN', // 众安的clientcode
    CLIENT_CODE_LEXINBAO_RISK: 'LEXINBAO_RISK', // 乐新宝碎屏险
    CLIENT_CODE_PATICA: 'PaTica', // 意时碎屏险
    ZHONGAN_SHANHS_WD_CODE: 'SHSXNWD', // 众安-闪回收虚拟维修网点
    MENU_TYPE_MENU: 1,
    MENU_TYPE_BUTTUN: 2,
    MENU_TYPE_OTHER: 3,
    EDIT_SUFFIX: ':put',
    CREATE_SUFFIX: ':post',
    DELETE_SUFFIX: ':delete',
    LIST_SUFFIX: ':get',
    ORDER_TYPE_SHUNFENG: 1,
    ORDER_TYPE_EXPRESS: 2,
    ORDER_TYPE_SHOP: 3,
    ORDER_TYPE_DOOR: 4,
    ORDER_TYPE_MINI: 5, // 1 顺丰上门 2 自寄 3 到店,4：上门 5小程序
    CHANNEL_STATUS_NORMAL: 1,
    CHANNEL_STATUS_STOP: 0,
    CHANNEL_STATUS_OPEN: 2,
    CHANNEL_STATUS_COMMIT: 3,
    AUTHORIZATION_HEADER: 'Authorization',
    JD_DETECTION_PRICE_TEMP: 2,
    USER_TYPE_SHANHS: 1,
    USER_TYPE_AREA: 2,
    USER_TYPE_SHUNFENG: 3,
    ORDER_STATUS_WAITING_SUBMIT: 4, // 待审核
    ORDER_STATUS_WAITING_SEND: 5, // 待发货
    ORDER_STATUS_GOING_DOOR: 6, // 上门中
    ORDER_STATUS_EXPRESS_ERROR: 9, // 物流异常
    ORDER_STATUS_IS_DOOR: 10, // 已上门
    ORDER_STATUS_WAITING_DETECTION: 11, // 待检测
    ORDER_STATUS_WAITING_BARGIN_PRICE: 21, // 待议价
    ORDER_STATUS_WAITING_RETURN: 25, // 退还
    ORDER_STATUS_WAITING_STORAGE: 31, // 待入库
    ORDER_STATUS_BLEAM_WAITING_STORAGE: 32, // 待入库
    ORDER_STATUS_STORAGE: 30, // 已入库
    ORDER_STATUS_FINDOUTIFY: 37, // 追责判断
    ORDER_STATUS_WAITING_FINDOUT: 38, // 待追责
    ORDER_STATUS_WAITING_IMAGE: -34, // 待上传
    ORDER_STATUS_WAITING_SUBMIT33: -33, // 待提交
    ORDER_STATUS_SEND_BACK: -20, // 待追责
    ORDER_STATUS_CLOSE: -10, // 待追责
    ORDER_STATUS_RECHECK: 15, // 复检
    ORDER_STATUS_PAYMENT: 40, // 已付款
    SECOND_STATUS_NORMAL: 0,
    SECOND_STATUS_HAND_UP: 1,
    SECOND_STATUS_STORAGE: -1,
    PRODUCT_CHECK_TYPE_ONLINE: 1,
    PRODUCT_CHECK_TYPE_OFFLINE_MANUAL: 2,
    PRODUCT_CHECK_TYPE_OFFLINE_AUTO: 3,
    PRODUCT_CHECK_TYPE_NINGXIA: 4, // 宁夏 已停用
    PRODUCT_CHECK_TYPE_OFFLINE_MINI_APP: 5,
    PRODUCT_CHECK_TYPE_ONLINE_MINI_APP: 6,
    ARTICLE_STATUS_DELETE: 0,
    ARTICLE_STATUS_DRAFT: 1,
    ARTICLE_STATUS_PUBLISH: 2,
    SALE_METHOD_SALE: 1, // 商品出售方式，出售
    SALE_METHOD_RENTAL: 2, // 商品出售方式，租赁
    GOODS_TYPE_ENTITY: 1, // 实物类商品
    GOODS_TYPE_VIRTUAL: 2, // 虚拟类商品
    GOODS_TYPE_COUPON: 3, // 卡券类商品
    RENTAL_ORDER_STATUS_TIMEOUT_CANCEL: -22, // 超时取消 -22
    RENTAL_ORDER_STATUS_MANUAL_CANCEL: -21, // 手动取消 -21
    RENTAL_ORDER_STATUS_PROCESS_MAINTAIN: -13, // 处理维修 -13
    RENTAL_ORDER_STATUS_PROCESS_BACK: -12,  // 处理退机 -12
    RENTAL_ORDER_STATUS_PROCESS_CANCEL: -11,  // 处理取消 -11
    RENTAL_ORDER_STATUS_WAIT_PAY: 2,  // 等待支付
    RENTAL_ORDER_STATUS_WAIT_SEND: 3,  // 等待发货
    RENTAL_ORDER_STATUS_WAIT_RECEIVE: 4,  // 等待收货
    RENTAL_ORDER_STATUS_FINISH: 5,    // 已完成
    RENTAL_ORDER_STATUS_PAYOUT: 6,   // 已买断
    GOODS_CHANNEL_STATUS_ON_SHELF: 1, // 渠道商品状态，上架
    GOODS_CHANNEL_STATUS_OFF_SHELF: 0, // 渠道商品状态，下架
    AFTER_SALE_TYPE_MAINTAIN: 3, // 维修
    AFTER_SALE_TYPE_BACK: 2, // 退机
    AFTER_SALE_TYPE_CANCEL: 1, // 取消
    AFTER_SALE_CANCLE_STATUS: -10, // 取消状态
    AFTER_SALE_CREATE_STATUS: 0, // 订单创建状态（待审核）
    AFTER_SALE_WAIT_DELIVEING: 2,  // 待发货
    AFTER_SALE_WAIT_RECEIVING: 3,  // 待收货
    AFTER_SALE_WAIT_CHECK: 4, // 待检测 （总部收货）
    AFTER_SALE_SEND_OUT: 10,   // 总部发货
    AFTER_SALE_SERVICE_FINISH: 20,   // 售后完成
    RISK_ACCOUNT_TYPE_ZFB: 1, // 支付宝
    RISK_ACCOUNT_TYPE_BANK: 11, // 银行卡
    RISK_ACCOUNT_TYPE_BANK2: 12, // 银行卡
    RISK_STATUS_WAIT_AUDIT: 2,
    RISK_STATUS_AUDIT_SUCCESS: 3,
    RISK_STATUS_WAIT_PAY: 1,
    RISK_STATUS_HANG_UP: 0,
    RISK_STATUS_AUDIT_CANCEL: -1,
    RISK_STATUS_APPLY: 4, // 申保中
    RISK_STATUS_WAIT_SUPPLIER_AUDIT: 23, // 供应商
    RISK_STATUS_WAIT_AFTER: 24, // 代售后确认
    RISK_STATUS_APPLY_SUCCESS: 30, // 维修中
    RISK_STATUS_FIXED_SUCCESS: 40, // 理赔通过待打款
    RISK_STATUS_RISK_PAYED: 50, // 财务已打款
    RISK_STATUS_ORDER_CANCEL: -40, // 作废
    RISK_STATUS_CANCEL_REFUND_ING: -11,
    RISK_STATUS_WAITING_BOSS_AUDIT: 21,
    RISK_STATUS_WAIT_CUSTOMER_CONFIRM: 22,
    RISK_STATUS_REJECT_ORDER: 20,
    RISK_STATUS_ACTIVE: 10, // 生效中
    RISK_STATUS_TIMEOUT_CANCEL: -2, // 超时作废
    RISK_AUDIT_TYPE_NORMAL_ORDER: 1,
    RISK_AUDIT_TYPE_APPLY_CHANGE: 2,
    RISK_AUDIT_TYPE_APPLY_REFUND: 3,
    RISK_AUDIT_TYPE_APPLY_CLAIM: 4,
    RISK_AUDIT_TYPE_REPAIR_FLOW: 5,
    RISK_AUDIT_TYPE_DELETE: -1,
    SUIPING_TYPE_PAY: 1,
    SUIPING_TYPE_SHOP: 2,
    SUIPING_TYPE_PRICE_DEFINE: 3,
    POST_ORDER_STATUS_SAVE: 0,
    POST_ORDER_STATUS_RECEIVE: 1,
    POST_ORDER_STATUS_SENDED: 2,
    POST_ORDER_STATUS_FAILD: -1,
    TICKET_TYPE_RECOVERY: 1, // 回收增值券
    TICKET_TYPE_MALL: 2, // 优品销售券
    TICKET_TYPE_QA_REWARD: 11, // 质量奖励红包
    TICKET_TYPE_RECOVERY_REWARD: 12, // 回收增值红包
    TICKET_TYPE_STUFF: 15, // 实物礼品
    TICKET_TYPE_STUFF_COUPON: 16, // 实物礼券
    TICKET_SEND_TYPE_OFFLINE_MEMBER: 1,
    TICKET_SEND_TYPE_SALEMAN: 2,
    TICKET_SEND_TYPE_SALEBOSS: 13,
    TICKET_SEND_TYPE_ONLINE_MEMBER: 21,
    PRIZE_TYPE_TICKET: 1, // 券
    PRIZE_TYPE_VIRTUAL: 2, // 虚拟商品
    PRIZE_TYPE_STUFF: 3, // 实物
    PRIZE_TYPE_INTEGRAL: 4, // 积分
    PRIZE_TYPE_RED_PACKAGE: 5, // 红包
    LUCK_REDPACKET_SMALL_REWARD: 6, // 幸运小奖
    ORDER_REDPACKET: 7, // 订单红包
    ACTIVITY_TARGET_MEMBER: 1,
    ACTIVITY_TARGET_SALEMAN: 11,
    ACTIVITY_TARGET_SALEBOSS: 12,
    ACTIVITY_TARGET_OFFLINE_CUSTOM: 13,
    USER_PRIZE_STATUS_NOT_SEND: 0, // 未发送
    USER_PRIZE_STATUS_SENDED: 1, // 发送中
    USER_PRIZE_STATUS_SENDING: 2, // 已发送
    ACTIVITY_TYPE_INTGRAL: 1, // 活动类型  积分抽奖
    ACTIVITY_TYPE_ONLINE: 2, // 活动类型  线上抽奖
    ACTIVITY_TYPE_OPERATE: 3, // 活动类型  运营活动
    SYSMODEL_TYPE_HUISHOU: 1, // 手机回收
    SYSMODEL_TYPE_ERSHOU: 2, // 二手优品
    SYSMODEL_TYPE_CHANNEL: 3, // 手机回收渠道商
    SYSMODEL_TYPE_SHANKU: 4, // 闪酷新品
    SYSMODEL_TYPE_PC: 5, // PC
    DETECTION_NOT_PAS: 1, // 检测不通过, 需要追责
    DETECTION_NOT_PAS_DO_NOTHING: 2, // 检测不通过, 不需要客服议价
    DETECTION_NEED_IMAGE: 3, // 检测不通过, 需要上传三张图片供客服议价
    DETECTION_PASS: 4, // 检测通过
    FINANCE_ACCOUNT_TYPE_ALIPAY: '1', // 支付宝
    FINANCE_ACCOUNT_TYPE_WECHAT_PAY: '2', // 微信支付
    FINANCE_ACCOUNT_TYPE_BANK: '3', // 银行
    FINANCE_ACCOUNT_TYPE_YIFUBAO_SHUNFENG: '11', // 易付宝顺维修
    FINANCE_ACCOUNT_TYPE_BANK_TRANSFAR: '12', // 银行转账
    FINANCE_ACCOUNT_TYPE_MINI_PAY: '22', // 小程序
    FINANCE_ACCOUNT_TYPE_YIFUBAO_SHANHS: '23', // 易付宝闪回收
    FINANCE_ACCOUNT_TYPE_ALI_MINI_PAY: '24', // 支付宝线上小程序付款
    PAY_DETAIL_STATUS_NOT_PAY: 0, // 未支付
    PAY_DETAIL_STATUS_PAYED: 1, // 已支付
    PAY_DETAIL_FORM_TYPE_PHONE: 1, // 手机回收款
    PAY_DETAIL_FORM_TYPE_SALE_PAY: 2, // 手机销售款
    PAY_DETAIL_FORM_TYPE_SHARE: 11, // 分享奖励
    PAY_DETAIL_FORM_TYPE_EXPRESS_FILL: 12, // 补快递费
    PAY_DETAIL_FORM_TYPE_SINGLE_QA_REWARD: 21, // 单台质量奖
    PAY_DETAIL_FORM_TYPE_MEMBER_RED_PACKAGE: 22, // 顾客红包
    PAY_DETAIL_FORM_TYPE_OVERFULFILLED_REWARD: 23, // 超额奖励
    PAY_DETAIL_FORM_TYPE_SEND_GOODS_REWARD: 24, // 发货奖励
    PAY_DETAIL_FORM_TYPE_SHOP_MANAGER_REWARD: 25, // 店长激进
    PAY_DETAIL_FORM_TYPE_SHOP_ADDED_TICKET: 26, // 门店增值券
    PAY_DETAIL_FORM_TYPE_SALEMAN_ENCOURAGE: 27, // 店长激进
    PAY_DETAIL_FORM_TYPE_OVERLYING_REWARD: 28, // 叠加奖励
    PAY_DETAIL_FORM_TYPE_FIRST_ORDER_REWARD: 29, // 首单奖励
    PAY_DETAIL_FORM_TYPE_CUSTOMER_ACTIVITY: 30, // 顾客活动
    PAY_DETAIL_FORM_TYPE_SINGLE_SALEMAN_REWARD: 31, // 单台店员奖
    PAY_DETAIL_FORM_TYPE_CHANNEL_CUT_PAYMENT: 32, // 渠道扣款
    PAY_DETAIL_FORM_TYPE_INTEGRAL_RED_PACKAGE: 33, // 积分红包
    PAY_DETAIL_FORM_TYPE_SHOP_RED_PACKAGE: 35, // 商城红包
    PAY_DETAIL_FORM_TYPE_LUCK_DRAW: 41, // 抽奖
    PAY_DETAIL_FORM_TYPE_SALE_COUPON: 51, // 销售优惠券
    PAY_DETAIL_FORM_TYPE_ZMXY_PRE_PAY: 52, // 芝麻信用预付款
    PAY_DETAIL_FORM_TYPE_SHANDIANJIANG_PAY: 53, // 线上闪电奖
    BARGAINING_STATUS_CREATED: 0,
    BARGAINING_STATUS_SUCCESS: 1,
    BARGAINING_STATUS_FAILED: 2,
    BOX_STATUS_OPEN: 1, // 正常状态， 开箱
    BOX_STATUS_CLOSE: 0, // 封箱
    BOX_STATUS_AUCTION: 2, // 竞价中
    GO_DOWN_ENTRY_TYPE_CHCEKIN: 'CHECKIN', // 检测入库
    GO_DOWN_ENTRY_TYPE_TRANSOUT: 'TRANSOUT', // 调拨出库
    GO_DOWN_ENTRY_TYPE_EXEMPT_CHECK_IN: 'EXEMPT_CHECK_IN', // 调拨出库
    SALE_OUT_STATUS_CREATED: 0, // 出库单状态， 创建，可编辑
    SALE_OUT_STATUS_SUBMIT_AUDIT: 1, // 提交审核
    SALE_OUT_STATUS_PASS: 2, // 审核通过
    SALE_OUT_STATUS_OUTED: 3, // 确认出库
    SALE_OUT_STATUS_RETURN: 4, // 退换货
    SALE_OUT_STATUS_RETURN_COMPLATE: 5, // 退换货完成
    SALE_OUT_STATUS_REPERTORY: 6, // 仓库确认
    SALE_OUT_STATUS_INVALID: -1, // 退换货完成
    SALE_OUT_ITEM_STATUS_NORMAL: 1, // 正常
    SALE_OUT_ITEM_STATUS_CHANGE: 2,  // 换货
    SALE_OUT_ITEM_STATUS_RETURN_REQUEST: 3, // 退货申请
    SALE_OUT_ITEM_STATUS_RETURN: -1,    // 退货
    ENABLE: 1, // 通用状态，启用
    DISABLE: 0, // 通用状态，禁用
    AUCTION_STATUS_EXPIRED: -1, // 已终止竞价
    AUCTION_STATUS_PUBLISH: 1, // 竞价中
    AUCTION_STATUS_SUBMIT: 2,
    AUCTION_STATUS_SUCCESS: 3, // 竞价成功
    PRODUCT_FINSTATUS_PAYED: 1,
    PRODUCT_FINSTATUS_UNPAY: 0,
    PRODUCT_FINSTATUS_CANCEL: -1,
    PRODUCT_FINSTATUS_RETURN: -3,
    CLIENT_TYPE_PERSON: 7,
    PRODUCT_TRANSFER_TYPE: 'TRANSFER_TYPE', // 机器转移类型
    THIRD_PRODUCT_TYPE: 'THIRD_PRODUCT_TYPE', // 第三方品名类型
    PAY_ORDER_CONFIRMED: 1,  // 付款已确认到账
    PAY_ORDER_NOT_CONFIRM: 0, // 付款未确认
    PAY_ORDER_STATUS_PAYED: 1, // 已付款
    PAY_ORDER_STATUS_PAYING: 2, // 付款中
    PAY_ORDER_STATUS_NOT_PAY: 0, // 未付款
    PD_PRODUCT_EXPROC_TYPE: 301, // 付款错误
    REPORT_EQUAL_TYPE_FROM_TO: 'FromTo',
    REPORT_DEFAULT_VALUE_TYPE_SYSTEM: 'sys',
    REPORT_REF_TYPE_DATA_SET: 'DataSet',
    REPORT_REF_TYPE_JSON: 'Json',
    REPORT_DATA_TYPE_DATE: 'date',
    DISCUSS_STATUS_AGREE: 1, // 可发布
    DISCUSS_STATUS_WAIT: 0, // 待发布
    DISCUSS_STATUS_CANNEL: -1, // 作废
    DISCUSS_TYPE_ONLINE: 0, // 线上
    DISCUSS_TYPE_OFFLINE: 1, // 线下
    AGREE_STATUS_AGREE: 1, // 满意
    AGREE_STATUS_UNAGREE: 0, // 不满意
    CHANNEL_LEVEL_CUSTOMER: 4, // 渠道级别客户
    CHANNEL_LEVEL_SHOP: 5, // 渠道级别 店铺
    PAY_FAIL_INFO: 'PAYFAILINFO', // 无法付款原因
    SETTLE_TYPE_RATIO: 1,   // 奖励比例
    SETTLE_TYPE_STEP: 2,    // 阶梯奖励
    SETTLE_TYPE_ATTAIN: 3,  // 达量奖励
    SETTLEMENT_COLLECTION_TYPE_AUTO_CREATED: 1,
    SETTLEMENT_COLLECTION_TYPE_CREATED_BY_USER: 20,
    SETTLEMENT_STATUS_CANCEL_SETTLEMENT: -1,
    SETTLEMENT_STATUS_CREATING: 0,
    SETTLEMENT_STATUS_CREATED: 1,
    SETTLEMENT_STATUS_WAITING_PROXY_AUDIT: 10,
    SETTLEMENT_STATUS_WAITING_BUSINESS_AUDIT: 20,
    SETTLEMENT_STATUS_WAITING_SHANHS_AUDIT: 30,
    SETTLEMENT_STATUS_WAITING_FINANCE_PAY: 40,
    SETTLEMENT_STATUS_FINANCE_PAY_SUCCESS: 50,
    DISCUSS_LABEL_PRICE: 'DISCUSS_PRICE',
    DISCUSS_LABEL_STYLE: 'DISCUSS_STYLE',
    DISCUSS_DISPOSE_STATUS_NORMAL: 1, // 评论已处理
    DISCUSS_DISPOSE_STATUS_WAIT: 0, // 评论待处理
    SYS_REFUND_STATUS: 'REFUNDSTATUS',  // 退款状态
    SYS_SALE_METHOD: 'SALE_METHOD', // 出售方式
    SYS_CHANNEL_TOP_LEVEL: 'CHANNEL_TOP_LEVEL', // 出售方式
    SYS_EXAMPLE_PICTURE_TYPE: 'EXAMPLE_PICTURE_TYPE',
    PRD_EXPROC_STATUS_WAIT: 0, // 未处理
    PRD_EXPROC_STATUS_EXPROCING: 1, // 处理中
    PRD_EXPROC_STATUS_EXPROCED: 2, // 已处理
    TIME_POINT_PRODUCT_CHECK_IN: 'PRODUCT_CHECK_IN',
    SYS_CODE_YOUPIN_CHECK_TYPE: 'YOUPIN_CHECK_TYPE', // 优品检测类型
    SYS_CODE_JD_PROCESSING_METHOD: 'JD_PROCESSING_METHOD', // 京东处理方式
    SYS_CODE_AUCTION_STATUS: 'AUCTION_STATUS', // 竞价单状态
    SYS_CODE_AUCTION_STATUS_MANAGE: 'AUCTION_STATUS_MANAGE', // 竞价单状态-管理端
    SYS_CODE_QUOTATION_STATUS: 'QUOTATION_STATUS', // 报价状态
    SETTLEMENT_RULE_USE_TYPE_RENTAL: 1, // 结算规则使用类型， 租机
    SETTLEMENT_RULE_USE_TYPE_RISK: 2, // 结算规则使用类型， 碎屏险
    SYS_THEME_LOCATION_TYPE: 'THEME_LOCATION', // 首頁主題位置類型
    SYS_THEME_CONTENT_TYPE: 'THEME_CONTENT',
    SYS_RETURN_VISIT_TYPE: 'RETURN_VISIT_TYPE',
    WHS_CHANNEL_ID: 11814,
    ADDR_POSITION_OUTER: 1, // 位置标识-外部
    ADDR_POSITION_INNER: 2, // 位置标识-公司内部
    SYS_DETECTION_TYPE: 'DETECTION_TYPE',
    SYS_ORDER_COMMENT_TYPE: 'ORDER_COMMENT_TYPE',
    SYS_APPEAL_STATUS: 'APPEAL_STATUS',
    MEIZU_JD_RISK_CHANNEL_ID: 36636,
    SYS_CHANNEL_EXPROC_STATUS: 'CHANNEL_EXPROC_STATUS',
    SYS_CHANNEL_EXPROC_TYPE: 'CHANNEL_EXPROC_TYPE',
    SYS_UNPACKING_STATUS: 'UNPACKING_STATUS', // 快递拆包状态
    SYS_CODE_DOOR_CHECK_TYPE: 'DOOR_CHECK_TYPE', // 检测类型
    SYS_CODE_DOOR_BUY_TYPE: 'DOOR_BUY_TYPE',    // 采购类型
    SYS_CODE_DOOR_CONFIRM_STATUS: 'DOOR_CONFIRM_STATUS',    // 审核状态
    SYS_ML_GOODS_STATUS: 'ML_GOODS_STATUS',
    SYS_CODE_ZHUANZHUAN_EXPRESS: 'ZHUANZHUAN_EXPRESS',    // 转转快递
    SYS_CODE_EXPRESS_TODOOR: 'EXPRESS_TODOOR',   // 快递上门
    SYS_CODE_ZHUANZHUAN_TYPE: 'ZHUANZHUAN_TYPE',    // 转转类型
    SYS_CODE_INVOICE_TYPE: 'INVOICE_TYPE',      // 发票类型
    SYS_CODE_TAX_RATE_TYPE: 'TAX_RATE_TYPE',    // 税率类型
    SYS_CODE_PURCHASE_ORDER_TYPE: 'PURCHASE_ORDER_TYPE', // 采购订单付款类型
    SYS_CODE_ALLOCATION_STORAGE_STATUS: 'ALLOCATION_STORAGE_STATUS',
    SYS_CODE_ONLINE_RECONC_ORG: 'ONLINE_RECONC_ORG',
    SYS_CODE_ADJUST_PRICE_STATUS: 'ADJUST_PRICE_STATUS',
    SYS_CODE_SALE_RETURN_STATUS: 'SALE_RETURN_STATUS',
    SYS_CODE_SALE_RETURN_TYPE: 'SALE_RETURN_TYPE',
    SYS_CODE_PAY_ACCOUNT_SWITCH: 'PAY_ACCOUNT_SWITCH',
    SYS_CODE_SALE_OUT_ORDER_TYPE: 'SALE_OUT_ORDER_TYPE',
    SYS_CODE_DETECTION_CLASSIFY_TYPE: 'DETECTION_CLASSIFY_TYPE',
    SYS_CODE_BOXTYPE: 'BOXTYPE',
    SYS_CODE_DETECTION_LEVEL: 'DETECTION_LEVEL',
    SYS_CODE_OPTION_QUALITY: 'OPTION_QUALITY',
    SYS_CODE_REWARD_SUPPLY_STATUS: 'REWARD_SUPPLY_STATUS'
}
